### ISSUE TITLE
Add Pagination Button and make all the grid element take all the space.

### ISSUE THREAD

**Issue by kunal-halder577** [imSyntn/PublicAPI_Hub#2]
**Is your feature request related to a problem? Please describe.**
The pagination at the bottom is small to navigate. And it kind a look out of place when there are still items but the items does not fill all the table.
![Screenshot 2024-02-16 155740](https://github.com/imSyntn/PublicAPI_Hub/assets/129545870/b7fe745c-acfa-48a6-8e51-245f743fc0ff)

**Describe the solution you'd like**
Add (<, >) pagination buttons to navigate the pages more efficiently. And if there are still items available fill all the tables with items.

**Comment by imSyntn** [comment]
Fixed it.
Thanks For Reporting🌟✌🏼.
